name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 執行腳本
        run: |
          echo 'hello world!' > ./wwwroot/about.html
      - name: 上傳成品檔
        uses: actions/upload-artifact@v3
        with:
          name: wwwroot
          path: ./wwwroot/

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: 下載成品檔
        uses: actions/download-artifact@v2
        with:
          name: wwwroot
      - name: 部屬至 IIS
        run: |
          Copy-Item . C:/inetpub/wwwroot/cicd-sample